import { Money } from "../../items/money.model.js";

export const billowProperties = [
  {
    id: crypto.randomUUID(),
    property: "Small Apartment",
    description:
      "Buy this affordable 1br/1ba small apartment, ideal for city living!",
    price: new Money({ dollars: 85_000 }),
    address: "910 Central Ave",
    beds: 1,
    baths: 1,
    year: 2005,
    condition: 80,
    features: [
      "Close to public transport",
      "Modern kitchen",
      "Secure building",
    ],
  },
  {
    id: crypto.randomUUID(),
    property: "Tiny House",
    description:
      "Buy this cozy 1br/1ba tiny house, perfect for minimalist living!",
    price: new Money({ dollars: 50_000 }),
    address: "1123 Minimalist St",
    beds: 1,
    baths: 1,
    year: 2018,
    condition: 85,
    features: ["Energy-efficient", "Open floor plan", "Low maintenance yard"],
  },
  {
    id: crypto.randomUUID(),
    property: "Studio Condo",
    description: "Buy this efficient studio condo, perfect for singles!",
    price: new Money({ dollars: 70_000 }),
    address: "789 Urban Blvd",
    beds: 0,
    baths: 1,
    year: 2010,
    condition: 75,
    features: ["Open living space", "Rooftop access", "Low HOA fees"],
  },
  {
    id: crypto.randomUUID(),
    property: "Country Cabin",
    description:
      "Buy this rustic 1br/1ba cabin in the countryside, perfect for a getaway!",
    price: new Money({ dollars: 90_000 }),
    address: "456 Woodland Rd",
    beds: 1,
    baths: 1,
    year: 1995,
    condition: 70,
    features: ["Wood-burning stove", "Wrap-around porch", "Large lot"],
  },
  {
    id: crypto.randomUUID(),
    property: "Mobile Home",
    description: "Buy this 2br/2ba mobile home, perfect for affordable living!",
    price: new Money({ dollars: 45_000 }),
    address: "321 Sunset Park",
    beds: 2,
    baths: 2,
    year: 2000,
    condition: 65,
    features: ["Community amenities", "Spacious layout", "Private parking"],
  },
  {
    id: crypto.randomUUID(),
    property: "City Loft",
    description:
      "Buy this stylish 1br/1ba city loft, perfect for young professionals!",
    price: new Money({ dollars: 95_000 }),
    address: "654 Downtown St",
    beds: 1,
    baths: 1,
    year: 2012,
    condition: 90,
    features: ["High ceilings", "Modern design", "Gym access"],
  },
  {
    id: crypto.randomUUID(),
    property: "Suburban House",
    description: "Buy this 3br/2ba suburban house, great for families!",
    price: new Money({ dollars: 98_000 }),
    address: "123 Family Ct",
    beds: 3,
    baths: 2,
    year: 1990,
    condition: 80,
    features: ["Fenced yard", "Two-car garage", "Quiet neighborhood"],
  },
];
