export const partTimeJobs = [
  {
    id: crypto.randomUUID(),
    job: "Coffee Shop Barista",
    description: "Apply for this part-time position today!",
    employer: "Brewed Awakenings",
    hourlyRate: 12,
    weeklyHours: 10,
  },
  {
    id: crypto.randomUUID(),
    job: "Fast Food Cook",
    description: "Apply for this part-time position today!",
    employer: "Quick Bites",
    hourlyRate: 11,
    weeklyHours: 15,
  },
  {
    id: crypto.randomUUID(),
    job: "Retail Sales Associate",
    description: "Apply for this part-time position today!",
    employer: "Trendy Threads",
    hourlyRate: 13,
    weeklyHours: 12,
  },
  {
    id: crypto.randomUUID(),
    job: "Library Assistant",
    description: "Apply for this part-time position today!",
    employer: "City Library",
    hourlyRate: 10,
    weeklyHours: 8,
  },
  {
    id: crypto.randomUUID(),
    job: "Dog Walker",
    description: "Apply for this part-time position today!",
    employer: "Paws and Tails",
    hourlyRate: 15,
    weeklyHours: 6,
  },
  {
    id: crypto.randomUUID(),
    job: "Movie Theater Usher",
    description: "Apply for this part-time position today!",
    employer: "Cineplex 10",
    hourlyRate: 9,
    weeklyHours: 10,
  },
  {
    id: crypto.randomUUID(),
    job: "Gas Station Attendant",
    description: "Apply for this part-time position today!",
    employer: "Fuel Up",
    hourlyRate: 12,
    weeklyHours: 12,
  },
];
